POST https://8080-marcelozang-projetoclub-0rcagz03j9k.ws-us110.gitpod.io/participantes
Content-Type: application/json

{
    "nome": "Nome de teste para comprovante",
    "registroFuncionario": 8461,
    "email": "nomedeteste@j.com.br"
}